sellermenu:
  header: ":offset_-48::slot2:"
  rows: 54
  items:
    vorona:
      slot: 45
      name: " "
      id: diamond_sword
      cmd: 10029
      lore: []
    vorona4:
      slot: 53
      name: " "
      id: diamond_sword
      cmd: 10021
      lore: []
    info:
      slot: 49
      name: " "
      id: EMERALD
      cmd: 10021
      lore:
        - '  %design_clr_main%              Скупщик  '
        - '  '
        - '  %design_clr_primary%Скупает %design_clr_main%почти все %design_clr_primary%предметы.  '
        - ' '
        - '  %design_clr_main%Учитывает:  '
        - '  %design_clr_primary%зачарования'
        - '  %design_clr_primary%паттерны брони'
        - '  %design_clr_primary%прочность и т.д  '
        - '  '
        - '  %design_clr_main%Перекиньте сюда  '
        - '  %design_clr_primary%продаваемые предметы  '
        - '  %design_clr_main%И закройте меню.  '
        - '  %design_clr_primary%Он автоматически купит шмот  '
        - ' '
    #empty лево
    empty0:
      slot: 0
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty9:
      slot: 9
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty18:
      slot: 18
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty27:
      slot: 27
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty36:
      slot: 36
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    #право
    empty8:
      slot: 8
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty17:
      slot: 17
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty26:
      slot: 26
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty35:
      slot: 35
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty44:
      slot: 44
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    #низ 46 47 48 50 51 52
    empty46:
      slot: 46
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty47:
      slot: 47
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty48:
      slot: 48
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty50:
      slot: 50
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty51:
      slot: 51
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty52:
      slot: 52
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
preview:
  header: ":offset_-48::slot2:"
  rows: 54
  items:
    vorona:
      slot: 45
      name: " "
      id: diamond_sword
      cmd: 10029
      lore: []
    vorona4:
      slot: 53
      name: " "
      id: diamond_sword
      cmd: 10021
      lore: []
    info:
      slot: 49
      name: " Вернуться назад  "
      id: EMERALD
      cmd: 10021
    #empty лево
    empty0:
      slot: 0
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty9:
      slot: 9
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty18:
      slot: 18
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty27:
      slot: 27
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty36:
      slot: 36
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    #право
    empty8:
      slot: 8
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty17:
      slot: 17
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty26:
      slot: 26
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty35:
      slot: 35
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty44:
      slot: 44
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    #низ 46 47 48 50 51 52
    empty46:
      slot: 46
      name: " "
      id: paper
      cmd: 10000
      lore: []
    empty47:
      slot: 47
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty48:
      slot: 48
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty50:
      slot: 50
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty51:
      slot: 51
      name: " "
      id: diamond_sword
      cmd: 10028
      lore: []
    empty52:
      slot: 52
      name: " "
      id: paper
      cmd: 10002
      lore: []