name: SatanicSeller
version: '1.0'
main: org.mrdarkimc.satanicseller.SatanicSeller
api-version: '1.21'
commands:
  seller:
    description: /seller
    aliases:
      - скупщик
      - ыуддук
  sprev:
    description: /preview
depend:
  - ItemWorth
  - SatanicMenusAPI